### ISSUE TITLE
Benchmark of ulive 

### ISSUE THREAD

**Issue by eramax** [kethan/ulive#1]
Hi, I liked your code, I did a benchmark on it please check it. I noticed it is very slow in compare with others, maybe you can fix the benchmark or the library.

[https://codesandbox.io/s/ulive-vs-usignal-vs-preact-1gnmbu](https://codesandbox.io/s/ulive-vs-usignal-vs-preact-1gnmbu
)
**USignal**
![image](https://user-images.githubusercontent.com/542413/199830724-f5201db6-09ed-4bb3-ab28-03e54db7e369.png)

**ULIVE**
![image](https://user-images.githubusercontent.com/542413/199830936-57d44323-654e-457a-b2b9-0b9e627c93e7.png)

Best,

**Comment by kethan** [comment]
Thanks for your interest. Yes I know the performance is not great but ok. The goal of the u prefixed library is to provide more features in less size rather than performance. In the near future if time permits will optimise in the same or create a new one. Even PR are welcomed.

**Comment by eramax** [comment]
That is great, thanks
